version: '3.8'

services:
  database:
    image: postgres:15
    container_name: community_bot_database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: community_bot_application
    build:
      context: ../../
      dockerfile: ../../Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
volumes:
  postgres_data: